### PR TITLE
Rubocop/rubocop-rspec update and git ignore file cleanup

### PR DESCRIPTION
**Pull request by madlew**
https://github.com/u2i/rspec-hive/issues/35

### CODE REVIEW

**Comment by madlew** [comment]
In the end I decided to clean up the git igore file because it seems it's outdated. Please let me know if I removed too much from it.

**Comment by jekuta** [comment]
@madlew You can try `bundle gem my_gem`. To see what would the recommended default options be.
http://bundler.io/v1.12/guides/creating_gem.html

Also you will need to delete the files (`Gemfile.lock`) that we don't want to be tracked from the repo.

**Comment by madlew** [comment]
ok, I'll look at it later on but I guess most of the entries I removed were OK (and I should revert them) because it's about supporting as many development/editor/os configurations as possible

**Comment by jekuta** [comment]
This is the default list for a newly created gem, so I think we should include at least that.
```
/.bundle/
/.yardoc
/Gemfile.lock
/_yardoc/
/coverage/
/doc/
/pkg/
/spec/reports/
/tmp/
```

**Comment by madlew** [comment]
btw. currently travis fails due to rubocop issue (gemspec gem alphabetical order) https://travis-ci.org/u2i/rspec-hive/jobs/290342606 but it doesn't fail on my local machine - any ideas why we have such a difference? why in docker we have slightly different results?

**Comment by madlew** [comment]
and speaking of the defaults you mentioned (and now I know where they come from, thx!): why do we have /Gemfile.lock not just 'Gemfile.lock'? it doesn't work with '/'

**Comment by jekuta** [comment]
> A leading slash matches the beginning of the pathname. For example, "/*.c" matches "cat-file.c" but not "mozilla-sha1/sha1.c".

https://git-scm.com/docs/gitignore

So `/Gemfile.lock` matches the one that is directly in the same path as .gitignore, but not if the file is in a subfolder.

You can try out the change yourself in an empty folder with git.

```
.
├── Gemfile.lock
├── a
└── b
    ├── Gemfile.lock
    └── a
```
If you add `/Gemfile.lock` to the `.gitignore` only the one in root ignored. If you add just `Gemfile.lock` both the files are ignored.

**Comment by madlew** [comment]
such a small change but I learn so much from it! thx! ;)

**Comment by jekuta** [comment]
Are you running the same version of rubocop on your local machine as the one on travis? This check that is failing on Travis was introduced in 0.51.0 https://github.com/bbatsov/rubocop/blob/master/CHANGELOG.md#0510-2017-10-18

**Comment by madlew** [comment]
@jekuta speaking of failing travis - it seems it just installed a new rubocop version ..released yesterday;) so it's an interesting case and probably it's not only about removing Gemfile.lock

I think we should also change:
````gem 'rubocop', '~> 0.50'````
to
````gem 'rubocop', '~> 0.50.0'````
because since they don't use major versioning so (their minor is actually their major) so with this configuration we're too optimistic with the autoupdate

**Comment by jekuta** [comment]
Yeah, rubocop quite often releases new version that create new issues. I'm fine with restricting the version. But then we just need to remember to update it every now and then. Since the issues it reports are usually worth looking into.

**Comment by madlew** [comment]
@wmiel @jekuta @nowNick - please give it a look again.

**Pull request merged**
