### PR TITLE
Feature/load udfs parametrized

### PR DESCRIPTION
**Pull request by quirk0o**
@nowNick 
@mknapik 
Could you take a look? 
We might need to execute the modified rake task on Jenkins before certain rspec-hive tests. Let me know what you think.

### CODE REVIEW

**Comment by mknapik** [comment]
@quirk0o It's not related to your changes and it's rather some unpinned gems updates but it would be nice to fix the build first.

**Comment by nowNick** [comment]
Looks nice :)

**Comment by nowNick** [comment]
@quirk0o @wmiel  What's the status of this PR?

**Comment by nowNick** [comment]
@quirk0o @wmiel Ping

**Pull request closed without merging**
