### PR TITLE
Gem name change - switched name to RSpec::Hive:: <<classes here>>

### PR DESCRIPTION
**Pull request by nowNick**

### CODE REVIEW

**Comment by nowNick** [comment]
@mknapik and @wmiel please review

**Comment by mknapik** [comment]
@nowNick Overall looks great.
I think we should rename `spec/rspec/hive_tests_spec.rb` to `spec/rspec/hive_spec.rb`.
I'd adjust README as well.

**Comment by wmiel** [comment]
@nowNick Git is stupid and can't tell these files were renamed but probably there is nothing we can do about this. The rest looks good :+1:

**Comment by mknapik** [comment]
Also consider changing the name of `hive_tests_config.yml`. E.g. `rspec_hive.yml`.

**Comment by nowNick** [comment]
Ok. I fiexed README.md and renamed file and renamed it but to `rspec-hive.yml` to keep it consistent. Ready to merge?

**Comment by nowNick** [comment]
This fixes #6

**Pull request merged**
